import{a as b,i as w,s as L}from"./assets/vendor-dbdbd0f5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const q=document.querySelector(".form"),d=document.querySelector("#input"),p=document.querySelector(".gallery"),i=document.querySelector(".loader"),l=document.querySelector(".load-more-btn");let c=1,u="";i.style.display="none";l.style.display="none";q.addEventListener("submit",async r=>{r.preventDefault(),u=d.value.trim(),p.innerHTML="",d.value="",i.style.display="block",c=1,l.style.display="none",await y()});l.addEventListener("click",async()=>{i.style.display="block",await y();const r=v();k(r*2)});async function y(){const r=new URLSearchParams({key:"41777094-15d23fa072ac8c02efe5e3565",q:u,image_type:"photo",orientation:"horizontal",safesearch:"true",page:c,per_page:40});try{const o=await b.get(`https://pixabay.com/api/?${r}`);if(!o.data.hits||!o.data.hits.length)w.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",backgroundColor:"#EF4040",titleColor:"white",messageSize:"16",titleSize:"16",position:"topRight",maxWidth:430});else{const a=o.data.hits.reduce((e,{webformatURL:t,largeImageURL:s,tags:m,likes:f,views:g,comments:h,downloads:S})=>e+`<li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${t}" alt="${m}" />
          </a>          
          <div class="description">
            <p>Likes:<span>${f}</span></p>
            <p>Views:<span>${g}</span></p>
            <p>Comments:<span>${h}</span></p>
            <p>Downloads:<span>${S}</span></p>
          </div> 
        </li>`,"");p.innerHTML+=a,new L("ul.gallery a",{captionDelay:250,captionsData:"alt"}).refresh(),o.data.totalHits>c*40?l.style.display="block":l.style.display="none",c++}}catch(o){i.style.display="none",console.log(o)}finally{i.style.display="none"}}function v(){const r=document.querySelector(".gallery-item");return r?r.getBoundingClientRect().height:0}function k(r){const o=performance.now(),a=600,n=e=>{const t=e-o;window.scrollBy({top:r*Math.sin(t/a*(Math.PI/2)),behavior:"smooth"}),t<a&&requestAnimationFrame(n)};requestAnimationFrame(n)}
//# sourceMappingURL=commonHelpers.js.map
